### ISSUE TITLE
Running script/server on Ubuntu 16.04 results into "Failed to obtain Ruby KFramework object when booting"

### ISSUE THREAD

**Issue by jfkverhamme** [haplo-org/haplo#10]
After installing and running server/script the script ends with a final message "Failed to obtain Ruby KFramework object when booting".

`myUserName@myHostname:/media/myUserName/DATA/myData/workspaceIntelliJ/haplo$ script/server
===============================================================================
               Haplo Platform (c) Haplo Services Ltd 2006 - 2016
             Licensed under the Mozilla Public License Version 2.0
===============================================================================
Starting framework in /media/myUserName/DATA/myData/workspaceIntelliJ/haplo with environment development
Loading server SSL certificates from /home/myUserName/haplo-dev-support/certificates
 - server cert chain length 1, public server

   **** PLUGIN DEBUGGING ENABLED ****

Platform components available: pdfbox
Exception in boot.rb: #<Errno::ENOENT: No such file or directory - /home/myUserName/haplo-dev-support/khq-dev/plugins/loader.dev>
org/jruby/RubyDir.java:461:in `mkdir'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/1.9/fileutils.rb:247:in `fu_mkdir'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/1.9/fileutils.rb:176:in `mkdir'
org/jruby/RubyArray.java:1613:in `each'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/1.9/fileutils.rb:175:in `mkdir'
/media/myUserName/DATA/myData/workspaceIntelliJ/haplo/app/develop_plugin/developer_loader.rb:38:in `DeveloperLoader'
/media/myUserName/DATA/myData/workspaceIntelliJ/haplo/app/develop_plugin/developer_loader.rb:12:in `(root)'
org/jruby/RubyKernel.java:1072:in `require'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/gems/shared/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:242:in `require'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/gems/shared/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:225:in `load_dependency'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/gems/shared/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:597:in `new_constants_in'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/gems/shared/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:596:in `new_constants_in'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/gems/shared/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:225:in `load_dependency'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/gems/shared/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:242:in `require'
/media/myUserName/DATA/myData/workspaceIntelliJ/haplo/config/loaded.rb:1:in `(root)'
org/jruby/RubyArray.java:1613:in `each'
/media/myUserName/DATA/myData/workspaceIntelliJ/haplo/config/loaded.rb:18:in `(root)'
org/jruby/RubyKernel.java:1072:in `require'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/gems/shared/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:242:in `require'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/gems/shared/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:225:in `load_dependency'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/gems/shared/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:597:in `new_constants_in'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/gems/shared/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:596:in `new_constants_in'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/gems/shared/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:225:in `load_dependency'
/home/myUserName/haplo-dev-support/vendor/jruby/lib/ruby/gems/shared/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:242:in `require'
/media/myUserName/DATA/myData/workspaceIntelliJ/haplo/config/loaded.rb:18:in `(root)'
org/jruby/RubyKernel.java:1072:in `require'
/media/myUserName/DATA/myData/workspaceIntelliJ/haplo/framework/boot.rb:1:in `(root)'
/media/myUserName/DATA/myData/workspaceIntelliJ/haplo/framework/boot.rb:98:in `(root)'
Failed to obtain Ruby KFramework object when booting
`

**Comment by bensummers** [comment]
Just to check,

Have you run db/init_dev_db.sh before running script/server ?

Does ~/haplo-dev-support/khq-dev/plugins exist, and is writable by the server's user?

Thanks.
