### ISSUE TITLE
Schema requirements apply for feature std:navigation silently fails if characters other than [a-zA-Z0-9:-] used in position name

### ISSUE THREAD

**Issue by thomas-** [haplo-org/haplo#11]
Discovered when trying to figure out why certain items wouldn't be added to the navigation automatically when included in requirements.schema - failing items had underscores in the names

Manually adding works, and generating schema requirements will include the name with underscores for example, but applying those schema requirements will not add the navigation position

Think it's this regex that's restricting it:

https://github.com/haplo-org/haplo/blob/e6280ac8f1ce7eaf929b54cc08e3e88c17f4b708/lib/schema_requirements_app.rb#L323-L329

**Comment by bensummers** [comment]
I think you're asking for a more relaxed regexp (adding _ at least) **and** a warning?

**Comment by thomas-** [comment]
Yeah I think both would make it pretty clear for anyone else who would stumble into this.

This isn't a breaking or at all urgent issue, but felt worth reporting (mostly due to the schema generator outputting things it won't read!)

**Comment by bensummers** [comment]
Added the _ and the error message, and this change will go out in the next open source release.
