### ISSUE TITLE
Broken link in GeoLite2 setup.

### ISSUE THREAD

**Issue by simolon** [haplo-org/haplo#12]
The Geolite2 link is no longer working. It seems I could fix it, but am not sure if everything is still in order and allowed according to their license. 
I am experiencing further issues using the setup script on Ubuntu 16.04. I am not sure if this might be connected to the problem. If you could confirm that this fix solves the GeoLite issue and should not affect the rest of the setup, I will post a sepoarate issue about the rest of my problem.

```
$ diff fetch-and-compile.sh_fixed fetch-and-compile.sh
193,195c193,195
< MAXMIND_DB_VERSION=20190430
< MAXMIND_DB_DIGEST=a6f58d5c4511c448d3a428d09e5cc8794db109db
< MAXMIND_DB_FILENAME=GeoLite2-Country.tar.gz
---
> MAXMIND_DB_VERSION=20180911
> MAXMIND_DB_DIGEST=b077bc6ebe3e30f293eb7a668928cabe9cab6550
> MAXMIND_DB_FILENAME=GeoLite2-Country_${MAXMIND_DB_VERSION}.tar.gz
```

Thanks a lot.

**Comment by bensummers** [comment]
Fixing that link won't affect anything else, so I would very much appreciate hearing of any other issues.

We're about to do a release, and will fix the script as part of our release engineering.

Thanks!

**Comment by simolon** [comment]
Thanks for your reply. Nice to hear about the new release. I saw the archive and checksum changing as it is still updated. I did a dirty workaround for that, but I am sure you will fix this for good in the updated script. I am opening another ticket for the other issue.
