### ISSUE TITLE
Installation script fails on Ubuntu 16.04 WirtualBox guest on Win 10 host

### ISSUE THREAD

**Issue by simolon** [haplo-org/haplo#13]
Hi,

after having worked around the GeoLite2 issue I am encountering further problems when running the installation script on a clean install of Ubuntu 16.04 Server in a VirtualBox on a Win 10 host.

I attached the files I used to patch the installation script (with txt extension as github appears picky). It seems to always fail on the first run. In one case, re-running the script it went through.

The last time I tried it from scratch, it did not succeed, even on the second try.

I now can access the server, but not log in. Could this be an issue due to some lag during stratup of some services from running it in a virtual machine?

The last lines of the first run were
```
[...]
Enter the name for this site: A
Enter the name of the first user: B
Enter the email of the first user: simonhk@or.is
Enter the password of the first user: C
 *** Configuring application for haplo.simonserver.test
EXCEPTION IN RUNNER: #<RuntimeError: bad initial user real name> (see server logs for more details)
RuntimeError: bad initial user real name
  method_missing at /opt/haplo/vendor/jruby/lib/ruby/1.9/drb/drb.rb:1140
          (root) at framework/console_client.rb:92
 *** Haplo application for haplo.simonserver.test initialized ***

Browse to
  http://haplo.simonserver.test/
And log in as the user you created above.

   *** Welcome to Haplo ***
$
```

[install.sh.txt](https://github.com/haplo-org/haplo/files/3149906/install.sh.txt)
[haplo-install.sh.patch.txt](https://github.com/haplo-org/haplo/files/3149907/haplo-install.sh.patch.txt)

**Comment by bensummers** [comment]
Could you try again, and when prompted for "Enter the name of the first user" enter something with a space, for example "B C", and confirm the error message in the middle of the logs is no longer present?

Just to confirm, did you see the initial Haplo login page when you visited the URL?

/cc @ptribble

**Comment by simolon** [comment]
Hi Ben,

thanks for the pointer. I can confirm that I could see the login page and navigate there, just not log in. I had abbreviated my input during the trials as I got tired of it, probably caused a new problem with that.

My last trial got a bit further and throws a different error:

```
Enter the name for this site: Haplo Test
Enter the name of the first user: Test User
Enter the email of the first user: simonhk@or.is
Enter the password of the first user: XXXXX
 *** Configuring application for haplo.simonserver.test
WARNING: user password does not meet security requirements
EXCEPTION IN RUNNER: #<ActiveRecord::RecordInvalid: Validation failed: Email is not a valid email address> (see server logs for more details)
DRb::DRbUnknownError: ActiveRecord::RecordInvalid
  method_missing at /opt/haplo/vendor/jruby/lib/ruby/1.9/drb/drb.rb:1136
          (root) at framework/console_client.rb:92
 *** Haplo application for haplo.simonserver.test initialized ***

Browse to
  http://haplo.simonserver.test/
And log in as the user you created above.

   *** Welcome to Haplo ***
$
```
Same issues regarding the login. I am sure that this email is a valid one ;-) I am running it again with another address. 

Where could I find the mentioned server logs? Screened briefly for them but could not find anything in the obvious locations.

**Comment by bensummers** [comment]
I'm sorry for all the problems you're having. We need to make this setup script a bit more robust, and will do so ASAP.

It's not liking the email address for some reason. It should be accepted (I just tested it passes validation). Could you make absolutely sure there is no whitespace around the email?

Logs are in /haplo/log

Thanks for your patience.

**Comment by simolon** [comment]
I re-ran it with my personal email. Went through with the warning about a weak password, understandably.

I shall run it again with the failing email and pay attention to inserting it as it is. I will report back.

May I abuse this for a quick follow-up question? I looked at your documentation but did not find anything that helped me. If I want now install the haplo-repository and haplo-research-manager, or plugins, how would I do that? Can you point me to the right place in your docs, if available?

**Comment by bensummers** [comment]
Great. Sounds like our setup script needs to be much more robust. Your feedback is very much appreciated.

There's some notes here on a quick start with Docker for Haplo Repository:

https://github.com/haplo-org/haplo-repository

To upload plugins into a development server which is running from a checkout of the haplo git repository:

Install the plugin tool: https://docs.haplo.org/dev/tool/plugin/install-unix

Then check out the git repositories next to each other, then see the instructions here under "Upload the plugin to your development server":

https://haplo.org/documentation/develop-plugin

In the haplo-repository git repository, use the command:

haplo-plugin -p hresrepodemo_application

This will then install and configure everything in the demo repository application.

**Comment by simolon** [comment]
Thanks a lot Ben!

I ran the script again and it worked with the other email. I might have entered an escape sequence trying to enter the "@" in the setup keyboard layout. This resolves my issues with the haplo-setup. Looking forward to test the next release as well.

Regarding the other question, thanks for the instructions. I had to see that i only looked at the "pinned projects" on this site, so I missed the other projects. I think I will get far with your instructions and see how it goes.

Thanks again!

**Comment by bensummers** [comment]
My pleasure. You've been very helpful in reporting the problems you've encountered.

I'm going to leave this issue open until we have resolved the issues with the setup script and our documentation.

**Comment by simolon** [comment]
Hi again. One more issue here, as it could be connected to the setup script. I hope I got the workflow correct, but in any way here is what I did and what I saw.

1. installing haplo with the script, giving haplo.simonserver.test as URL. Set name, username, email, password. Can access site and log in through web interface.
2. Installing the plugin-tool using https://raw.githubusercontent.com/haplo-org/haplo-plugin-tool/master/install/haplo_plugin_install.sh . (I installed it on the server, is that an issue?)
3. Following the instructions here, https://haplo.org/documentation/develop-plugin the "haplo-plugin auth" aborts due to wrong certificate. I see that the one in ~/haplo-dev-support/certificates/server.crt and /haplo/sslcerts/server.crt differ.
4. using /haplo/sslcerts/server.crt I can run haplo-plugin, but get an error from the server.
```
~/x$ cp /haplo/sslcerts/server.crt .
~/x$ haplo-plugin auth haplo.simonserver.test:8443
Haplo Plugin Tool (33a3b9b)
NOTICE: Using alternative CAs for SSL from server.crt
Requesting token from https://haplo.simonserver.test:8443 ...
Server returned an error. Check hostname and port.
```
The server logs show during this request
```
==> /haplo/log/app.log <==
Request: 2019-05-07T11:16:03Z GET /api/plugin-tool-auth/start-auth
  app: 4000
  params: {"name":"ubuntu"}
Incorrect URL requested /api/plugin-tool-auth/start-auth

==> /haplo/log/http.log <==
2019-05-07 11:16:03,560 127.0.0.1 haplo.simonserver.test GET /api/plugin-tool-auth/start-auth?name=ubuntu 404 111 111 i 44 34 TLS_DHE_RSA_WITH_AES_256_CBC_SHA "-" "plugin-tool"
```

So I can connect to the server it seems, using the certificate from /haplo/sslcerts/ but the server does not understand the request. 

Did I miss something in the server setup or is my approach wrong? If I should move this issue to another repository, please let me know.

Thanks in advance!

**Comment by simolon** [comment]
Thanks again Ben. This solved it. I had followed the production server instructions...
I will look more into all this once I got back from vacation. Looking forward to get this all to work and see the system in action!

**Comment by bensummers** [comment]
Glad it's all sorted now. You've given us lots of pointers to improve documentation, thank you.

I'd be very curious about what your potential application for Haplo, and see if I can help. Would you like to send me an email? ben.summers @ the obvious domain.

**Comment by ptribble** [comment]
I've pushed some updates to the install script, so that it validates user input in essentially the same way as the application, and we should no longer pass bad input through.

**Comment by bensummers** [comment]
@simolon Does the revised documentation here https://docs.haplo.org/platform address the issues you found? Thanks for all your feedback.
