### ISSUE TITLE
When running script/server, fails with UnknownHostException: haplo.local

### ISSUE THREAD

**Issue by ruckc** [haplo-org/haplo#8]
When running as described in http://haplo.org/documentation/build/ubuntu on script/server it fails with UnknownHostException: haplo.local

I tried recreating certificates from haplo-dev-support/certificates.

**Comment by bensummers** [comment]
What's the hostname? Does it contain any dots? If so, can you try a name without dots?

The server process needs to work out what name is being broadcast with multicast DNS. It's probably getting it wrong.
